
require("busted.runner")
require("types")
require("support")

describe("true_p test", function()
	it("tests various types", function()
		assert.False(true_p(nil))
		assert.True(true_p(true))
		assert.False(true_p(false))
		assert.False(true_p(0))
		assert.False(true_p(1))
		assert.False(true_p(""))
		assert.False(true_p("a"))
		assert.False(true_p(Symbol.new("a")))
		assert.False(true_p(Cons.new("a", "b")))
	end)
end)

describe("list test", function()
	it("tests", function()
		assert.are.same(list(), nil)
		assert.are.same(list(1), Cons.new(1, nil))
		assert.are.same(list(1, 2), Cons.new(1, Cons.new(2, nil)))
	end)
end)
